### ISSUE TITLE
500 Internal Server Error on /search.

### ISSUE THREAD

**Issue by haykkh** [haykkh/spotty-search#21]
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

when searching API
```
2020-02-06T12:47:02.221728+00:00 app[web.1]: [2020-02-06 12:47:02,221] ERROR in app: Exception on /search/killer [GET]

2020-02-06T12:47:02.221742+00:00 app[web.1]: Traceback (most recent call last):

2020-02-06T12:47:02.221746+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/fuzzywuzzy/process.py", line 68, in extractWithoutOrder

2020-02-06T12:47:02.221771+00:00 app[web.1]:     raise StopIteration

2020-02-06T12:47:02.221774+00:00 app[web.1]: StopIteration

2020-02-06T12:47:02.221776+00:00 app[web.1]: 

2020-02-06T12:47:02.221778+00:00 app[web.1]: The above exception was the direct cause of the following exception:

2020-02-06T12:47:02.221779+00:00 app[web.1]: 

2020-02-06T12:47:02.221781+00:00 app[web.1]: Traceback (most recent call last):

2020-02-06T12:47:02.221783+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app

2020-02-06T12:47:02.221784+00:00 app[web.1]:     response = self.full_dispatch_request()

2020-02-06T12:47:02.221786+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request

2020-02-06T12:47:02.221788+00:00 app[web.1]:     rv = self.handle_user_exception(e)

2020-02-06T12:47:02.221790+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function

2020-02-06T12:47:02.221791+00:00 app[web.1]:     return cors_after_request(app.make_response(f(*args, **kwargs)))

2020-02-06T12:47:02.221793+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception

2020-02-06T12:47:02.221794+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)

2020-02-06T12:47:02.221796+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise

2020-02-06T12:47:02.221797+00:00 app[web.1]:     raise value

2020-02-06T12:47:02.221799+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request

2020-02-06T12:47:02.221800+00:00 app[web.1]:     rv = self.dispatch_request()

2020-02-06T12:47:02.221802+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request

2020-02-06T12:47:02.221804+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)

2020-02-06T12:47:02.221806+00:00 app[web.1]:   File "/app/spotty_search/search/controllers.py", line 24, in searcher

2020-02-06T12:47:02.221807+00:00 app[web.1]:     results = fuzzy_search(query, spot.playlists_and_tracks)

2020-02-06T12:47:02.221809+00:00 app[web.1]:   File "/app/spotty_search/search/__init__.py", line 31, in fuzzy_search

2020-02-06T12:47:02.221810+00:00 app[web.1]:     results = process.extractBests(

2020-02-06T12:47:02.221812+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/fuzzywuzzy/process.py", line 194, in extractBests

2020-02-06T12:47:02.221813+00:00 app[web.1]:     sorted(best_list, key=lambda i: i[1], reverse=True)

2020-02-06T12:47:02.221815+00:00 app[web.1]: RuntimeError: generator raised StopIteration

2020-02-06T12:47:02.222747+00:00 app[web.1]: 10.65.69.10 - - [06/Feb/2020:12:47:02 +0000] "GET /search/killer HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
```

Seems to be an [issue with fuzzywuzzy](https://stackoverflow.com/questions/57207276/fuzzy-wuzzy-returning-runtimeerror?noredirect=1) and [PEP 479](https://www.python.org/dev/peps/pep-0479/).

**Comment by haykkh** [comment]
So fuzzywuzzy repo has been updated with a [fix](https://github.com/seatgeek/fuzzywuzzy/commit/1c018b733cc933aa6a57fa61a2350fa9975f5816) but they haven't updated the pypi release. Inquired [here](https://github.com/seatgeek/fuzzywuzzy/pull/243) but may have to fork and build myself.
